# <center>LSTM ON AMAZON DATASET

In [63]:
import os
import pandas as pd
import numpy as np

In [64]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [65]:
os.chdir(r"D:\Imarticus\Time Series And Deep Learning\NLP")

amazon=pd.read_csv("amazonreviews.tsv",sep="\t")

amazon  

label                                             review
0      pos  Stuning even for the non-gamer: This sound tra...
1      pos  The best soundtrack ever to anything.: I'm rea...
2      pos  Amazing!: This soundtrack is my favorite music...
3      pos  Excellent Soundtrack: I truly like this soundt...
4      pos  Remember, Pull Your Jaw Off The Floor After He...
5      pos  an absolute masterpiece: I am quite sure any o...
6      neg  Buyer beware: This is a self-published book, a...
7      pos  Glorious story: I loved Whisper of the wicked ...
8      pos  A FIVE STAR BOOK: I just finished reading Whis...
9      pos  Whispers of the Wicked Saints: This was a easy...
10     neg  The Worst!: A complete waste of time. Typograp...
11     pos  Great book: This was a great book,I just could...
12     pos  Great Read: I thought this book was brilliant,...
13     neg  Oh please: I guess you have to be a romance no...
14     neg  Awful beyond belief!: I feel I have to write t...
15     neg  Don't try to fool us with fake reviews.: It's ...
16     pos  A romantic zen baseball comedy: When you hear ...
17     pos  Fashionable Compression Stockings!: After I ha...
18     pos  Jobst UltraSheer Thigh High: Excellent product...
19     neg  sizes recomended in the size chart are not rea...
20     neg  mens ultrasheer: This model may be ok for sede...
21     pos  Delicious cookie mix: I thought it was funny t...
22     neg  Another Abysmal Digital Copy: Rather than scra...
23     pos  A fascinating insight into the life of modern ...
24     pos  i liked this album more then i thought i would...
25     neg  Problem with charging smaller AAAs: I have had...
26     neg  Works, but not as advertised: I bought one of ...
27     neg  Disappointed: I read the reviews,made my purch...
28     neg  Oh dear: I was excited to find a book ostensib...
29     pos  Based on the reviews here I bought one and I'm...
30     neg  Incorrect disc!: I am a big JVC fan, but I do ...
31     pos  happy with it...but: I'm a JVC nut...I have 3 ...
32     neg  should be titled "Hollywood Debacle": The plot...
33     pos  Is this great TV??? You bet it is: Hotel Babyl...
34     neg  Nothing you don't already know: If you have ev...
35     neg  Unfortunately it wasn't entertaining in the le...
36     pos  Rochelle explains It All for You: Wondering wh...
37     pos  More great playing: Larry's work for the Muse ...
38     neg  Doesn't work on a Mac: It clearly says on line...
39     neg  Very Frustrating: My three year old son was ve...
40     neg  Mind numbing: This game makes you do the same ...
41     neg  Cannot recommend: As a former Alaskan, I didn'...
42     pos  Alaska sourdough: REad most of the book while ...
43     pos  Old and good: This book is worth to keep in yo...
44     pos  autumn: got this for my daughter in NC, she is...
45     pos  Fast mp3 download of music waxed decades ago: ...
46     neg  Maybe I got a bad one.: My experience: I got t...
47     pos  Sylvania 6620LDG 20" Flat Panel LCD TV with Bu...
48     neg  TERRIBLE!! DO NOT BUY THIS: I bought this for ...
49     neg  *** BEWARE ***: This TV is set so that it is n...
50     pos  Kitchen TV: I bought this to replace a 13" tub...
51     pos  Nice for the money: The first one I bought was...
52     neg  Disappointed Romanian!: This book in my opinio...
53     pos  Great travel guide to Europe!: This book is re...
54     neg  Not the best: I bought both this and lonely pl...
55     pos  Good but received defective book: I bought thi...
56     pos  From The Label:: From Memphis, TN. comes The R...
57     neg  Either 1 or 5 Stars. Depends on how you look a...
58     pos  Hunting the Hard Way: Thia was a gift for my H...
59     neg  Disappointing: The text is the same as ever (I...
60     pos  Homer or Moses?: An extremely helpful gem on a...
61     neg  Very poor quality.: The screen arrived in a ca...
62     neg  Scraped across the whole top.: Purchased this ...
63     pos  unknown Africa: You don't

In [66]:
amazon.label.replace({"pos":1,"neg":0},inplace=True)

In [67]:
amazon.head()

label                                             review
0      1  Stuning even for the non-gamer: This sound tra...
1      1  The best soundtrack ever to anything.: I'm rea...
2      1  Amazing!: This soundtrack is my favorite music...
3      1  Excellent Soundtrack: I truly like this soundt...
4      1  Remember, Pull Your Jaw Off The Floor After He...

In [68]:
amazon.label.value_counts()

0    5097
1    4903
Name: label, dtype: int64

In [69]:
amazon_x=amazon.iloc[:,1]
amazon_y=amazon.iloc[:,0]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(amazon_x,amazon_y,test_size=0.2)

In [70]:
from keras.utils.np_utils import to_categorical
from tensorflow.keras.utils import to_categorical

y_train= to_categorical(y_train)
y_test=to_categorical(y_test)

In [71]:
y_test

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [72]:
## HyperParameters 
max_num_words=1200    ## How many words do we consider from the entire CORPUS(Coll of doc)
seq_len =100          ## how many token (Word to consider in each document/message)
embedding_size= 100   ## Vector length of each word

In [73]:
from keras_preprocessing.text import Tokenizer  # Is used for tokinization
from keras_preprocessing.sequence import pad_sequences # Used to bring all samples to same length

### <font color="red">What is Tokenizer and pad_sequences

In [74]:
tokenizer= Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(amazon.review)     ## Would be used to assign the token
x_train=tokenizer.texts_to_sequences(x_train) ## Will convert the text to sequence of IDs
x_train=pad_sequences(x_train,maxlen=seq_len)

In [75]:
x_train.shape

(8000, 100)

In [76]:
x_train[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
         24,   13,   32,   26,    3,  127,  157,  210, 1166,    3,  273,
          1,   68,    2,  144,    7,    5,   25,  758,   45,    3,  363,
          3,  340,    2,  369,    4,  266,   24,   83,    3,   21,   16,
        272,  180,    1,   68,   24,   46,    4,    2,    9,   16,  210,
        659,   57,  368,   11,   22,    7,   46,   88,  180,   58,   11,
        284])

In [77]:
x_test=tokenizer.texts_to_sequences(x_test) 
x_test=pad_sequences(x_test,maxlen=seq_len)

In [78]:
from keras.models import Model,Sequential
from keras.layers import Dense,LSTM,Embedding
from tensorflow.keras.optimizers import Adam

In [79]:
model=Sequential()  # Initialize the network
model.add(Embedding(input_dim=max_num_words, ## Embedding takes input in sequence and gives output in embedding
                   input_length= seq_len,
                   output_dim=embedding_size))
model.add(LSTM(50))
model.add(Dense(2,activation='softmax'))
from tensorflow.keras.optimizers import Adam
adam =Adam(learning_rate=0.01)

In [80]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [81]:
model.fit(x_train,y_train,epochs=8)

Epoch 1/8
250/250 [==============================] - 12s 38ms/step - loss: 0.5112 - accuracy: 0.7501
Epoch 2/8
250/250 [==============================] - 9s 36ms/step - loss: 0.3441 - accuracy: 0.8579
Epoch 3/8
250/250 [==============================] - 9s 38ms/step - loss: 0.2910 - accuracy: 0.8844
Epoch 4/8
250/250 [==============================] - 10s 38ms/step - loss: 0.2704 - accuracy: 0.8931
Epoch 5/8
250/250 [==============================] - 10s 40ms/step - loss: 0.2341 - accuracy: 0.9114
Epoch 6/8
250/250 [==============================] - 10s 41ms/step - loss: 0.2153 - accuracy: 0.9209
Epoch 7/8
250/250 [==============================] - 10s 39ms/step - loss: 0.1965 - accuracy: 0.9256
Epoch 8/8
250/250 [==============================] - 10s 42ms/step - loss: 0.2034 - accuracy: 0.9215


In [82]:
#getting model performance metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, roc_auc_score

In [83]:
y_pred = np.argmax(model.predict(x_test), axis=-1)
y_pred

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [84]:
y_test[:,1]

array([1., 0., 1., ..., 0., 0., 0.], dtype=float32)

In [85]:
tab=confusion_matrix(y_pred,y_test[:,1])
tab

array([[829, 158],
       [159, 854]], dtype=int64)

In [86]:
tab.diagonal().sum()/tab.sum()

0.8415

### Datset 2

In [87]:
spam=pd.read_csv("spam1.csv",encoding='cp1252')
spam.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [88]:
spam=spam.iloc[:,[0,1]] # dropping last 3 columns

In [89]:
spam.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [90]:
spam.rename(columns={"v1":"label","v2":"message"},inplace=True)

In [91]:
spam.label.replace({"ham":0,"spam":1},inplace=True)

In [92]:
spam_x=spam.iloc[:,1]
spam_y=spam.iloc[:,0]

x_train1,x_test1,y_train1,y_test1=train_test_split(spam_x,spam_y,test_size=0.2)

In [93]:
y_train1= to_categorical(y_train1)
y_test1=to_categorical(y_test1)

In [94]:
y_train1

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [95]:
## HyperParameters 
max_num_words=1200    ## How many words do we consider from the entire CORPUS(Coll of doc)
seq_len =100          ## how many token (Word to consider in each document/message)
embedding_size= 100   ## Vector length of each word

In [96]:
tokenizer= Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(spam.message)     ## Would be used to assign the token
x_train1=tokenizer.texts_to_sequences(x_train1) ## Will convert the text to sequence of IDs
x_train1=pad_sequences(x_train1,maxlen=seq_len)

In [97]:
x_train1.shape,y_train1.shape

((5420, 100), (5420, 2))

In [98]:
x_test1=tokenizer.texts_to_sequences(x_test1) 
x_test1=pad_sequences(x_test1,maxlen=seq_len)

In [99]:
model=Sequential()  # Initialize the network
model.add(Embedding(input_dim=max_num_words, ## Embedding takes input in sequence and gives output in embedding
                   input_length= seq_len,
                   output_dim=embedding_size))
model.add(LSTM(50))
model.add(Dense(2,activation='softmax'))
from tensorflow.keras.optimizers import Adam
adam =Adam(learning_rate=0.01)

In [100]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [101]:
model.fit(x_train1,y_train1,epochs=8)

Epoch 1/8
170/170 [==============================] - 10s 45ms/step - loss: 0.2004 - accuracy: 0.9367
Epoch 2/8
170/170 [==============================] - 8s 46ms/step - loss: 0.0394 - accuracy: 0.9897 4s -
Epoch 3/8
170/170 [==============================] - 8s 46ms/step - loss: 0.0221 - accuracy: 0.9945
Epoch 4/8
170/170 [==============================] - 8s 47ms/step - loss: 0.0131 - accuracy: 0.9961
Epoch 5/8
170/170 [==============================] - 8s 45ms/step - loss: 0.0109 - accuracy: 0.9970
Epoch 6/8
170/170 [==============================] - 8s 46ms/step - loss: 0.0090 - accuracy: 0.9978
Epoch 7/8
170/170 [==============================] - 8s 44ms/step - loss: 0.0053 - accuracy: 0.9991
Epoch 8/8
170/170 [==============================] - 8s 45ms/step - loss: 0.0029 - accuracy: 0.9993


In [102]:
y_pred1 = np.argmax(model.predict(x_test1), axis=-1)
y_pred1

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [103]:
tab1=confusion_matrix(y_pred1,y_test1[:,1])
tab1

array([[1163,    9],
       [   8,  176]], dtype=int64)

In [104]:
tab1.diagonal().sum()/tab1.sum()

0.9874631268436578

### Dataset 3

In [121]:
Trip=pd.read_csv("Trip_advisor_review.csv")

In [122]:
Trip.head()

Rating                                             Review
0       4  nice hotel expensive parking got good deal sta...
1       2  ok nothing special charge diamond member hilto...
2       3  nice rooms not 4* experience hotel monaco seat...
3       5  unique, great stay, wonderful time hotel monac...
4       5  great stay great stay, went seahawk game aweso...

In [123]:
Trip_x=Trip.iloc[:,1]
Trip_y=Trip.iloc[:,0]

x_train2,x_test2,y_train2,y_test2=train_test_split(Trip_x,Trip_y,test_size=0.2)

In [124]:
y_train2= to_categorical(y_train2)
y_test2=to_categorical(y_test2)

In [126]:
y_train2[5]

array([0., 0., 0., 0., 0., 1.], dtype=float32)

In [127]:
tokenizer= Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(spam.message)     ## Would be used to assign the token
x_train2=tokenizer.texts_to_sequences(x_train2) ## Will convert the text to sequence of IDs
x_train2=pad_sequences(x_train2,maxlen=seq_len)

In [128]:
x_test2=tokenizer.texts_to_sequences(x_test2) 
x_test2=pad_sequences(x_test2,maxlen=seq_len)

In [155]:
x_train2.shape,y_train2.shape

((16392, 100), (16392, 5))

In [146]:
#y_train2 =  y_train2[: , 1::]


In [147]:
#y_train2[:,0]

In [152]:
model1=Sequential()  # Initialize the network
model1.add(Embedding(input_dim=max_num_words, ## Embedding takes input in sequence and gives output in embedding
                   input_length= seq_len,
                   output_dim=embedding_size))
model1.add(LSTM(50))
model1.add(Dense(5,activation='softmax'))
from tensorflow.keras.optimizers import Adam
adam =Adam(learning_rate=0.01)

In [153]:
model1.compile(optimizer= 'adam', loss='categorical_crossentropy', metrics = ['accuracy'])

In [154]:
model1.fit(x_train2,y_train2,epochs=2)

Epoch 1/2
513/513 [==============================] - 24s 42ms/step - loss: 1.1427 - accuracy: 0.5001
Epoch 2/2
513/513 [==============================] - 22s 43ms/step - loss: 1.0079 - accuracy: 0.5622


In [140]:
con_mat = confusion_matrix(y_pred2, np.argmax(y_test2 , axis = 1))
con_mat


array([[ 132,   66,   20,    9,   16],
       [  60,  130,   71,   41,   22],
       [  12,   48,   74,   44,   18],
       [  17,   59,  140,  454,  238],
       [  45,   87,   95,  684, 1517]], dtype=int64)

In [141]:
con_mat.diagonal().sum()/con_mat.sum()

0.5628202000487924